name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull new commits
        run: git pull
        working-directory: /home/pi/nanideshiko-bot
      - name: Restart bot service
        run: sudo systemctl restart nanideshiko
